# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c3150f0117ce85ecbf8f252d143c0eb370ad73b47d34185e131184c25e8deefd088861e6c0b986b06c58a5d1abfd41bdbf5ec4862b7d8422ee188243c7dcd24

test:
  secret_key_base: 1e4aa38fce4c8a083d32b10efbf483380902aee54d6530c09c01b742b506e01a861f939d99a8b94d1b332cf0983eec47bd95f1dbb5d2a9ed0762978dd0e8109d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
